language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# Waiting for "official" support
# https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-405506964
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - pip install -U pip
  - sudo apt-get update -q
  # Workaround travis issue
  - sudo apt-get install -y --reinstall build-essential
install:
  - pip install .[test]
script:
  # Ensure we are testing installed app, not local code
  - mkdir -p /tmp/sandbox && cd /tmp/sandbox
  - pytest --pyargs uwsgi_pylib.tests.tests
